### ISSUE TITLE
App crashes after trying to add data the second time

### ISSUE THREAD

**Issue by katzuv** [arimb/ScantronScouter#1]
Steps to reproduce:
1. Open app
2. Click "Add Data" and choose some photo
3. Processed image pops up.
4. Close it without saving it.
5. When trying to click one of the buttons, the app becomes unresponsive and crashes.

**Comment by arimb** [comment]
I couldn't replicate the problem on 2 different computers. I did just push an update to fix a problem with the image window not disappearing after saving/closing, so maybe that fixed your problem too?

**Comment by katzuv** [comment]
Yes, looks good now. Thanks!
